//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WareHouse.Service
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
	using System.Data.Entity.ModelConfiguration.Conventions;

	public partial class WareHouseEntities : DbContext
    {
        public WareHouseEntities()
            : base("name=WareHouseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
			modelBuilder.Conventions.Remove<PluralizingTableNameConvention>();
            throw new UnintentionalCodeFirstException();
		}
    
        public virtual DbSet<User> Users { get; set; }
    }
}
